---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
      port: 5000
      targetPort: 5000
  selector:
      app: phpmyadmin
      tier: phpmyadmin
      type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              value: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password