---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
      port: 5050
      targetPort: 5050
  selector:
      app: wordpress
      tier: wordpress
      type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 5050
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              value: username
            - name: WORDPRESS_DB_PASSWORD
              value: password
           - name: WORDPRESS_DB_NAME
               value: wordpress